/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package rpsls.gui;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import rpsls.exceptions.InvalidNameException;
import rpsls.models.Player;

/**
 *
 * @author Xenocyde
 */
public class PlayerNameFrame extends javax.swing.JFrame {

    /**
     * Creates new form PlayerNameForm
     */
    public PlayerNameFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameText = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        continueButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nameText.setText("Enter the name of the player");

        nameLabel.setText("Name: ");

        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        continueButton.setText("Continue");
        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(continueButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(nameLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(nameTextField))
                        .addComponent(nameText)))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(nameText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(continueButton)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed
        Player newPlayer = new Player();
        String player;
        String name = this.nameTextField.getText();
        try {
        newPlayer.setName(name);
        MainMenuFrame mainMenuFrame = new MainMenuFrame();
        mainMenuFrame.setPlayer(newPlayer);
//        mainMenuFrame.getWelcomeLabel().setText("\nWelcome " + name + "!\n");
        // Easter eggs
        if("Sheldon".equals(name)){
            mainMenuFrame.getWelcomeLabel().setText("Welcome, Dr. Cooper. Your brillance is going to make this game great!\n Unless of course Wil Wheaton is playing. Then you're doomed!");
        }
        else if("Raj".equals(name)){
            mainMenuFrame.getWelcomeLabel().setText("Welcome, Dr. Koothrappali. I hope you are drunk.\n There might be a girl here.");
        }
        else if("Howard".equals(name)){
            mainMenuFrame.getWelcomeLabel().setText("Welcome, MISTER Wolowitz. Go get your doctorate, you bum!\n Also, stop fantazing about Kara Thrace and George Takei!");
        }
        else if("Leonard".equals(name)){
            mainMenuFrame.getWelcomeLabel().setText("Welcome, Dr. Hofstadter.\n How's the roommate agreement treating you? Treat Penny well. You don't deserve her.");
        }
        else if("Penny".equals(name)){
            mainMenuFrame.getWelcomeLabel().setText("Welcome, Penny. Do you even have a last name? Stay with Leonard.\n He's better than your beefy boyfriends.");
        }
        else if("Amy".equals(name)){
           mainMenuFrame.getWelcomeLabel().setText("Welcome, Dr. Folwer.\n How can you stand to be Sheldon's girlfriend. Are you insane?!"); 
        }
        else if("Bernadette".equals(name)){
            mainMenuFrame.getWelcomeLabel().setText("Welcome, Dr. Rostenkowski-Wolowitz.\n Howard chose you over his hand and Kara Thrace. Don't you feel lucky?");
        }
        else if("Wil".equals(name)){
            mainMenuFrame.getWelcomeLabel().setText("Welcome, Wil.\n You're going to own Sheldon Cooper at this game.");
        }   
        
        else{
            mainMenuFrame.getWelcomeLabel().setText("\nWelcome " + name + "!\n");
        }
        mainMenuFrame.setVisible(true);        
        this.dispose();
        }
        catch (InvalidNameException e) {
            continueButtonActionPerformed(evt);
        }
    }//GEN-LAST:event_continueButtonActionPerformed

    public JButton getContinueButton() {
        return continueButton;
    }

    public void setContinueButton(JButton continueButton) {
        this.continueButton = continueButton;
    }

    public JLabel getNameLabel() {
        return nameLabel;
    }

    public void setNameLabel(JLabel nameLabel) {
        this.nameLabel = nameLabel;
    }

    public JLabel getNameText() {
        return nameText;
    }

    public void setNameText(JLabel nameText) {
        this.nameText = nameText;
    }

    public JTextField getNameTextField() {
        return nameTextField;
    }

    public void setNameTextField(JTextField nameTextField) {
        this.nameTextField = nameTextField;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayerNameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayerNameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayerNameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayerNameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayerNameFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton continueButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameText;
    private javax.swing.JTextField nameTextField;
    // End of variables declaration//GEN-END:variables
}
